package com.gustavobatista.autoconfig.exception;

public enum ErrorCode {

    USER_NOT_FOUND,
    CAR_NOT_FOUND,
    CLIENT_NOT_FOUND,
    ORDER_NOT_FOUND,
    ACCESSORY_NOT_FOUND,
    VEHICLE_ENTRY_NOT_FOUND,

    CAR_DUPLICATE,
    CLIENT_PHONE_CONFLICT,
    VEHICLE_CHASSIS_CONFLICT,
    ACCESSORY_NAME_CONFLICT,

    ORDER_ACCESSORY_CAR_MISMATCH,

    FORBIDDEN,
    UNAUTHORIZED,

    VALIDATION_ERROR,

    INTERNAL_ERROR
}