UPDATE orders SET status = 'WAITING_FOR_ACCESSORY' WHERE status = 'VEHICLE_ARRIVED';
UPDATE orders SET status = 'WAITING_FOR_SCHEDULING' WHERE status = 'IN_INSTALLATION';
UPDATE orders SET status = 'READY_FOR_DELIVERY' WHERE status = 'READY';
