ALTER TABLE orders ADD COLUMN vehicle_arrived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN accessories_confirmed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN installation_completed BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE orders SET vehicle_arrived = TRUE WHERE status IN ('WAITING_FOR_ACCESSORY', 'WAITING_FOR_SCHEDULING', 'READY_FOR_DELIVERY');
UPDATE orders SET accessories_confirmed = TRUE WHERE status IN ('WAITING_FOR_SCHEDULING', 'READY_FOR_DELIVERY');
UPDATE orders SET installation_completed = TRUE WHERE status = 'READY_FOR_DELIVERY';

UPDATE orders SET status = 'WAITING_VEHICLE' WHERE status = 'WAITING_FOR_VEHICLE';
UPDATE orders SET status = 'WAITING_ACCESSORIES' WHERE status = 'WAITING_FOR_ACCESSORY';
UPDATE orders SET status = 'WAITING_SCHEDULING' WHERE status = 'WAITING_FOR_SCHEDULING';
